# Generated by Django 5.2 on 2025-07-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datas',
        ),
    ]
