# Generated by Django 5.2 on 2025-05-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='add',
        ),
    ]
