# Generated by Django 5.2 on 2025-05-16 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_home_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
